name: ui_extractor
description: Dart bindings for ui-extractor, a tool to extract UI element trees and text from screenshots.
version: 0.1.0
repository: https://github.com/SuiltaPico/ui-extractor
license: MIT

environment:
  sdk: ^3.4.0

platforms:
  android:
  windows:

dependencies:
  ffi: ^2.1.2
  path: ^1.9.0
  http: ^1.2.1
  archive: ^3.6.1
  native_assets_cli: ^0.5.0

dev_dependencies:
  lints: ^3.0.0
  ffigen: ^11.0.0
